/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Admin Application */
        post: operations["create_admin_application_api_v1_admin_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin-applications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Admin Application */
        get: operations["my_admin_application_api_v1_admin_applications_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/admin-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Applications */
        get: operations["list_admin_applications_api_v1_admin_admin_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/admin-applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Application */
        get: operations["get_admin_application_api_v1_admin_admin_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/admin-applications/{application_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Admin Application */
        post: operations["approve_admin_application_api_v1_admin_admin_applications__application_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/admin-applications/{application_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Admin Application */
        post: operations["reject_admin_application_api_v1_admin_admin_applications__application_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/factories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Factories */
        get: operations["list_factories_api_v1_admin_factories_get"];
        put?: never;
        /** Create Factory */
        post: operations["create_factory_api_v1_admin_factories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/factories/{factory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Factory */
        get: operations["get_factory_api_v1_admin_factories__factory_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Factory */
        patch: operations["update_factory_api_v1_admin_factories__factory_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/factory-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Factory Applications */
        get: operations["list_factory_applications_api_v1_admin_factory_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/factory-applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Factory Application */
        get: operations["get_factory_application_api_v1_admin_factory_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/factory-applications/{application_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Factory Application */
        post: operations["approve_factory_application_api_v1_admin_factory_applications__application_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/factory-applications/{application_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Factory Application */
        post: operations["reject_factory_application_api_v1_admin_factory_applications__application_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_admin_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin Users */
        get: operations["list_admin_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{target_user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Admin User */
        post: operations["disable_admin_user_api_v1_admin_users__target_user_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{target_user_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Admin User */
        post: operations["enable_admin_user_api_v1_admin_users__target_user_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/feishu/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complete Feishu Login */
        get: operations["complete_feishu_login_api_v1_auth_feishu_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/feishu/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Feishu Login */
        get: operations["start_feishu_login_api_v1_auth_feishu_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Web Logout */
        post: operations["web_logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Factory Options */
        get: operations["list_factory_options_api_v1_factories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factory-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Factory Application */
        post: operations["submit_factory_application_api_v1_factory_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factory-applications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Factory Application */
        get: operations["my_factory_application_api_v1_factory_applications_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current User */
        get: operations["current_user_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mini/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mini Logout */
        post: operations["mini_logout_api_v1_mini_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mini/auth/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mini Phone Binding */
        post: operations["mini_phone_binding_api_v1_mini_auth_phone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mini/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mini Refresh */
        post: operations["mini_refresh_api_v1_mini_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mini/auth/wechat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mini Wechat Login */
        post: operations["mini_wechat_login_api_v1_mini_auth_wechat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mini/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mini Avatar */
        get: operations["get_mini_avatar_api_v1_mini_me_avatar_get"];
        put?: never;
        /** Replace Mini Avatar */
        post: operations["replace_mini_avatar_api_v1_mini_me_avatar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sms/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Sms Challenge */
        post: operations["send_sms_challenge_api_v1_sms_challenges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminApplicationCreateRequest */
        AdminApplicationCreateRequest: {
            /** Challengeid */
            challengeId: string;
            /** Verificationcode */
            verificationCode: string;
        };
        /** AdminApplicationListResponse */
        AdminApplicationListResponse: {
            /** Items */
            items: components["schemas"]["AdminApplicationResponse"][];
            /** Total */
            total: number;
        };
        /** AdminApplicationResponse */
        AdminApplicationResponse: {
            /** Applicationid */
            applicationId: string;
            /** Displayname */
            displayName: string;
            /** Phonemasked */
            phoneMasked: string;
            /** Rejectionreason */
            rejectionReason: string | null;
            /** Reviewedat */
            reviewedAt: string | null;
            /** Reviewedby */
            reviewedBy: string | null;
            /** Status */
            status: string;
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            /** Userid */
            userId: string;
            /** Version */
            version: number;
        };
        /** AdminUserListResponse */
        AdminUserListResponse: {
            /** Items */
            items: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
        };
        /** ApproveFactoryApplication */
        ApproveFactoryApplication: {
            /** Factoryid */
            factoryId: string;
            /** Version */
            version: number;
        };
        /** AvatarResponse */
        AvatarResponse: {
            /** Fileid */
            fileId: number;
            /** Mimetype */
            mimeType: string;
            /** Sizebytes */
            sizeBytes: number;
        };
        /** Body_replace_mini_avatar_api_v1_mini_me_avatar_post */
        Body_replace_mini_avatar_api_v1_mini_me_avatar_post: {
            /** Avatar */
            avatar: string;
        };
        /** ContactResponse */
        ContactResponse: {
            /** Displayorder */
            displayOrder: number;
            /** Isprimary */
            isPrimary: boolean;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
        };
        /** ContactWrite */
        ContactWrite: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
        };
        /** FactoryApplicationCreate */
        FactoryApplicationCreate: {
            /** Factoryid */
            factoryId: string;
            /** Position */
            position: string;
            /** Realname */
            realName: string;
        };
        /** FactoryApplicationListResponse */
        FactoryApplicationListResponse: {
            /** Items */
            items: components["schemas"]["FactoryApplicationResponse"][];
            /** Total */
            total: number;
        };
        /** FactoryApplicationResponse */
        FactoryApplicationResponse: {
            /** Applicationid */
            applicationId: string;
            /** Boundfactoryid */
            boundFactoryId: string | null;
            /** Boundfactoryname */
            boundFactoryName: string | null;
            /** Factorycontacts */
            factoryContacts: components["schemas"]["ContactResponse"][];
            /** Phonemasked */
            phoneMasked: string;
            /** Position */
            position: string;
            /** Realname */
            realName: string;
            /** Rejectionreason */
            rejectionReason: string | null;
            /** Requestedfactoryid */
            requestedFactoryId: string;
            /** Requestedfactoryname */
            requestedFactoryName: string;
            /** Reviewedat */
            reviewedAt: string | null;
            /** Reviewedby */
            reviewedBy: string | null;
            /** Status */
            status: string;
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
            /** Userid */
            userId: string;
            /** Version */
            version: number;
        };
        /** FactoryListResponse */
        FactoryListResponse: {
            /** Items */
            items: components["schemas"]["FactoryResponse"][];
            /** Total */
            total: number;
        };
        /** FactoryOptionListResponse */
        FactoryOptionListResponse: {
            /** Items */
            items: components["schemas"]["FactoryOptionResponse"][];
            /** Total */
            total: number;
        };
        /** FactoryOptionResponse */
        FactoryOptionResponse: {
            /** Factoryid */
            factoryId: string;
            /** Factoryname */
            factoryName: string;
            /** Suppliernumber */
            supplierNumber: string;
        };
        /** FactoryResponse */
        FactoryResponse: {
            /** Address */
            address: string | null;
            /** Connectedusers */
            connectedUsers: number;
            /** Contacts */
            contacts: components["schemas"]["ContactResponse"][];
            /** Contractcomplete */
            contractComplete: boolean;
            /** Factorycode */
            factoryCode: string;
            /** Factoryid */
            factoryId: string;
            /** Factoryname */
            factoryName: string;
            /** Isenabled */
            isEnabled: boolean;
            /** Legalname */
            legalName: string | null;
            /** Legalrepresentative */
            legalRepresentative: string | null;
            /** Missingcontractfields */
            missingContractFields: string[];
            /** Suppliernumber */
            supplierNumber: string;
            /** Version */
            version: number;
        };
        /** FactoryUpdate */
        FactoryUpdate: {
            /**
             * Address
             * @default
             */
            address: string;
            /**
             * Contacts
             * @default []
             */
            contacts: components["schemas"]["ContactWrite"][];
            /** Factorycode */
            factoryCode: string;
            /** Factoryname */
            factoryName: string;
            /**
             * Legalname
             * @default
             */
            legalName: string;
            /**
             * Legalrepresentative
             * @default
             */
            legalRepresentative: string;
            /** Version */
            version: number;
        };
        /** FactoryWrite */
        FactoryWrite: {
            /**
             * Address
             * @default
             */
            address: string;
            /**
             * Contacts
             * @default []
             */
            contacts: components["schemas"]["ContactWrite"][];
            /** Factorycode */
            factoryCode: string;
            /** Factoryname */
            factoryName: string;
            /**
             * Legalname
             * @default
             */
            legalName: string;
            /**
             * Legalrepresentative
             * @default
             */
            legalRepresentative: string;
            /** Suppliernumber */
            supplierNumber: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MiniLoginResponse */
        MiniLoginResponse: {
            /** Bindingtoken */
            bindingToken: string | null;
            /** Rejectionreason */
            rejectionReason: string | null;
            session: components["schemas"]["SessionResponse"] | null;
            /** Status */
            status: string;
            user: components["schemas"]["UserResponse"] | null;
        };
        /** MiniRefreshRequest */
        MiniRefreshRequest: {
            /** Refreshtoken */
            refreshToken: string;
        };
        /** ProductListItemResponse */
        ProductListItemResponse: {
            /** Iid */
            iId: string;
            /** Imageavailable */
            imageAvailable: boolean;
            /** Name */
            name: string;
            /** Propertiesvalue */
            propertiesValue: string;
            /** Skuid */
            skuId: string;
            /** Variantid */
            variantId: string;
        };
        /** ProductListResponse */
        ProductListResponse: {
            /** Items */
            items: components["schemas"]["ProductListItemResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** RejectFactoryApplication */
        RejectFactoryApplication: {
            /** Reason */
            reason: string;
            /** Version */
            version: number;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Reason */
            reason: string;
            /** Version */
            version: number;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Version */
            version: number;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /** Refreshtoken */
            refreshToken: string | null;
        };
        /** SmsChallengeRequest */
        SmsChallengeRequest: {
            /** Phone */
            phone: string;
        };
        /** SmsChallengeResponse */
        SmsChallengeResponse: {
            /** Challengeid */
            challengeId: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /** Phonemasked */
            phoneMasked: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Capabilities */
            capabilities: string[];
            /** Displayname */
            displayName: string;
            /** Factoryid */
            factoryId: string | null;
            /** Factoryname */
            factoryName: string | null;
            /** Factoryposition */
            factoryPosition: string | null;
            /** Feishuavatarurl */
            feishuAvatarUrl: string | null;
            /** Isenabled */
            isEnabled: boolean;
            /** Issuperadmin */
            isSuperAdmin: boolean;
            /** Miniavatarexternalurl */
            miniAvatarExternalUrl: string | null;
            /** Miniavatarfileid */
            miniAvatarFileId: number | null;
            /** Phonemasked */
            phoneMasked: string | null;
            /** Role */
            role: string | null;
            /** Userid */
            userId: string;
            /** Version */
            version: number;
        };
        /** UserVersionRequest */
        UserVersionRequest: {
            /** Version */
            version: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WechatLoginRequest */
        WechatLoginRequest: {
            /** Code */
            code: string;
        };
        /** WechatPhoneRequest */
        WechatPhoneRequest: {
            /** Bindingtoken */
            bindingToken: string;
            /** Phonecode */
            phoneCode: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_admin_application_api_v1_admin_applications_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminApplicationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_admin_application_api_v1_admin_applications_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_applications_api_v1_admin_admin_applications_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_application_api_v1_admin_admin_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_admin_application_api_v1_admin_admin_applications__application_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_admin_application_api_v1_admin_admin_applications__application_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_factories_api_v1_admin_factories_get: {
        parameters: {
            query?: {
                keyword?: string;
                contractStatus?: string;
                accessStatus?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_factory_api_v1_admin_factories_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactoryWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_factory_api_v1_admin_factories__factory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                factory_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_factory_api_v1_admin_factories__factory_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                factory_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_factory_applications_api_v1_admin_factory_applications_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryApplicationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_factory_application_api_v1_admin_factory_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_factory_application_api_v1_admin_factory_applications__application_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveFactoryApplication"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_factory_application_api_v1_admin_factory_applications__application_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                application_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectFactoryApplication"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_admin_products_get: {
        parameters: {
            query?: {
                keyword?: string;
                page?: number;
                pageSize?: number;
                sortBy?: "iId" | "skuId" | "name" | "propertiesValue";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                role?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_admin_user_api_v1_admin_users__target_user_id__disable_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                target_user_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_admin_user_api_v1_admin_users__target_user_id__enable_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path: {
                target_user_id: string;
            };
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_feishu_login_api_v1_auth_feishu_callback_get: {
        parameters: {
            query: {
                state: string;
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_feishu_login_api_v1_auth_feishu_start_get: {
        parameters: {
            query?: {
                returnTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    web_logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_factory_options_api_v1_factories_get: {
        parameters: {
            query?: {
                keyword?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryOptionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_factory_application_api_v1_factory_applications_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactoryApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_factory_application_api_v1_factory_applications_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactoryApplicationResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_user_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mini_logout_api_v1_mini_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mini_phone_binding_api_v1_mini_auth_phone_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WechatPhoneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiniLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mini_refresh_api_v1_mini_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MiniRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mini_wechat_login_api_v1_mini_auth_wechat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WechatLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiniLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mini_avatar_api_v1_mini_me_avatar_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_mini_avatar_api_v1_mini_me_avatar_post: {
        parameters: {
            query?: never;
            header: {
                authorization?: string | null;
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_replace_mini_avatar_api_v1_mini_me_avatar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_sms_challenge_api_v1_sms_challenges_post: {
        parameters: {
            query?: never;
            header?: {
                "x-csrf-token"?: string | null;
            };
            path?: never;
            cookie?: {
                ot_web_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmsChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
