export const dashboardData = {
  updatedAt: "2026-08-12 15:40",
  stats: [
    {
      id: "pending-imports",
      label: "待导入订单",
      value: 6,
      unit: "单",
      detail: "其中 2 单资料待补",
      tone: "info",
      destination: "待导入订单",
    },
    {
      id: "pending-receipts",
      label: "待收货发货单",
      value: 4,
      unit: "张",
      detail: "今日新增 2 张",
      tone: "info",
      destination: "发货单列表 · 待收货",
    },
    {
      id: "overdue-orders",
      label: "逾期订单",
      value: 3,
      unit: "单",
      detail: "最久已逾期 4 天",
      tone: "danger",
      destination: "订单列表 · 仅看逾期",
    },
  ],
  notifications: [
    {
      id: "notification-1",
      title: "宇情工厂已提交发货",
      description: "FH20260812-004，涉及订单 369#",
      time: "10 分钟前",
      tone: "info",
      destination: "发货单 FH20260812-004",
    },
    {
      id: "notification-2",
      title: "订单 078# 已进入逾期",
      description: "昱斌工厂仍有 520 件待发",
      time: "今天 09:00",
      tone: "warning",
      destination: "订单 078#",
    },
    {
      id: "notification-3",
      title: "订单 090# 已确认收货",
      description: "本次实际收到 860 件",
      time: "昨天 17:42",
      tone: "success",
      destination: "订单 090#",
    },
  ],
  orders: [
    {
      id: "order-078",
      orderNo: "078#",
      productName: "乐园游会吊带包屁衣",
      category: "服装",
      tracker: "松子",
      factory: "昱斌、宇情",
      nearestDue: "2026-08-10",
      progress: 46,
      progressText: "1,380 / 3,000",
      status: "已逾期",
      tone: "danger",
    },
    {
      id: "order-369",
      orderNo: "369#",
      productName: "小热皮绒绒裤",
      category: "服装",
      tracker: "烧麦",
      factory: "宇情",
      nearestDue: "2026-08-13",
      progress: 72,
      progressText: "1,440 / 2,000",
      status: "发货中",
      tone: "info",
    },
    {
      id: "order-085",
      orderNo: "085#",
      productName: "海岛轻量防晒帽",
      category: "帽子",
      tracker: "青椒",
      factory: "盛泰",
      nearestDue: "2026-08-15",
      progress: 20,
      progressText: "480 / 2,400",
      status: "发货中",
      tone: "info",
    },
    {
      id: "order-088",
      orderNo: "088#",
      productName: "云朵软壳冲锋衣",
      category: "服装",
      tracker: "大葱",
      factory: "昱斌",
      nearestDue: "2026-08-18",
      progress: 0,
      progressText: "0 / 1,600",
      status: "待发货",
      tone: "warning",
    },
    {
      id: "order-090",
      orderNo: "090#",
      productName: "晴雨两用机能风衣",
      category: "服装",
      tracker: "橄榄",
      factory: "启宏",
      nearestDue: "2026-08-20",
      progress: 86,
      progressText: "860 / 1,000",
      status: "发货中",
      tone: "info",
    },
  ],
};

export const orderListData = {
  orders: [
    {
      id: "order-078",
      orderNo: "078#",
      productName: "乐园游会吊带包屁衣",
      category: "服装",
      specSummary: "3 个颜色 / 规格",
      tracker: "松子",
      factory: "昱斌、宇情",
      nearestDue: "2026-08-10",
      shippedPercent: 46,
      shippedText: "1,380 / 3,000",
      receivedPercent: 38,
      receivedText: "1,140 / 3,000",
      statusKey: "shipping",
      statusLabel: "发货中",
      tone: "danger",
      overdueDays: 3,
      orderDate: "2026-07-26",
      updatedAt: "2026-08-13T09:00:00",
    },
    {
      id: "order-369",
      orderNo: "369#",
      productName: "小热皮绒绒裤",
      category: "服装",
      specSummary: "2 个颜色 / 规格",
      tracker: "烧麦",
      factory: "宇情",
      nearestDue: "2026-08-13",
      shippedPercent: 72,
      shippedText: "1,440 / 2,000",
      receivedPercent: 54,
      receivedText: "1,080 / 2,000",
      statusKey: "shipping",
      statusLabel: "发货中",
      tone: "info",
      overdueDays: 0,
      orderDate: "2026-07-29",
      updatedAt: "2026-08-13T08:50:00",
    },
    {
      id: "order-085",
      orderNo: "085#",
      productName: "海岛轻量防晒帽",
      category: "帽子",
      specSummary: "4 个颜色 / 规格",
      tracker: "青椒",
      factory: "盛泰",
      nearestDue: "2026-08-15",
      shippedPercent: 20,
      shippedText: "480 / 2,400",
      receivedPercent: 0,
      receivedText: "0 / 2,400",
      statusKey: "shipping",
      statusLabel: "发货中",
      tone: "info",
      overdueDays: 0,
      orderDate: "2026-08-01",
      updatedAt: "2026-08-12T17:20:00",
    },
    {
      id: "order-088",
      orderNo: "088#",
      productName: "云朵软壳冲锋衣",
      category: "服装",
      specSummary: "5 个颜色 / 规格",
      tracker: "大葱",
      factory: "昱斌",
      nearestDue: "2026-08-18",
      shippedPercent: 0,
      shippedText: "0 / 1,600",
      receivedPercent: 0,
      receivedText: "0 / 1,600",
      statusKey: "pending",
      statusLabel: "待发货",
      tone: "warning",
      overdueDays: 0,
      orderDate: "2026-08-03",
      updatedAt: "2026-08-12T14:30:00",
    },
    {
      id: "order-090",
      orderNo: "090#",
      productName: "晴雨两用机能风衣",
      category: "服装",
      specSummary: "2 个颜色 / 规格",
      tracker: "橄榄",
      factory: "启宏",
      nearestDue: "2026-08-20",
      shippedPercent: 86,
      shippedText: "860 / 1,000",
      receivedPercent: 86,
      receivedText: "860 / 1,000",
      statusKey: "shipping",
      statusLabel: "发货中",
      tone: "info",
      overdueDays: 0,
      orderDate: "2026-08-04",
      updatedAt: "2026-08-12T11:10:00",
    },
    {
      id: "order-092",
      orderNo: "092#",
      productName: "轻量防风马甲等 2 款",
      category: "服装",
      specSummary: "7 个颜色 / 规格",
      tracker: "青椒",
      factory: "盛泰",
      nearestDue: "2026-08-22",
      shippedPercent: 0,
      shippedText: "0 / 2,800",
      receivedPercent: 0,
      receivedText: "0 / 2,800",
      statusKey: "draft",
      statusLabel: "草稿",
      tone: "draft",
      overdueDays: 0,
      orderDate: "2026-08-06",
      updatedAt: "2026-08-12T10:15:00",
    },
    {
      id: "order-096",
      orderNo: "096#",
      productName: "森林漫步速干短裤",
      category: "服装",
      specSummary: "3 个颜色 / 规格",
      tracker: "松子",
      factory: "宇情",
      nearestDue: "2026-08-08",
      shippedPercent: 100,
      shippedText: "1,200 / 1,200",
      receivedPercent: 100,
      receivedText: "1,200 / 1,200",
      statusKey: "completed",
      statusLabel: "已完成",
      tone: "success",
      overdueDays: 0,
      orderDate: "2026-07-18",
      updatedAt: "2026-08-10T16:40:00",
    },
    {
      id: "order-101",
      orderNo: "101#",
      productName: "山野轻暖摇粒绒",
      category: "服装",
      specSummary: "4 个颜色 / 规格",
      tracker: "烧麦",
      factory: "启宏",
      nearestDue: "2026-08-25",
      shippedPercent: 0,
      shippedText: "0 / 1,500",
      receivedPercent: 0,
      receivedText: "0 / 1,500",
      statusKey: "cancelled",
      statusLabel: "已取消",
      tone: "neutral",
      overdueDays: 0,
      orderDate: "2026-08-07",
      updatedAt: "2026-08-09T13:20:00",
    },
  ],
};

export const pendingImportData = {
  orders: [
    { orderNo: "E81", productName: "小护甲机能裤", category: "服装", tracker: "松子", factory: "宇情", validationKey: "ready", validationLabel: "可导入", tone: "success", statusKey: "pending" },
    { orderNo: "E82", productName: "云感防晒衣", category: "服装", tracker: "烧麦", factory: "昱斌", validationKey: "needs-data", validationLabel: "资料待处理", tone: "warning", statusKey: "pending" },
    { orderNo: "E83", productName: "海岛轻量防晒帽", category: "帽子", tracker: "青椒", factory: "盛泰", validationKey: "ready", validationLabel: "可导入", tone: "success", statusKey: "pending" },
    { orderNo: "E84", productName: "晴雨两用机能风衣", category: "服装", tracker: "橄榄", factory: "启宏", validationKey: "needs-data", validationLabel: "资料待处理", tone: "warning", statusKey: "pending" },
    { orderNo: "E85", productName: "森林漫步速干短裤", category: "服装", tracker: "大葱", factory: "宇情", validationKey: "needs-data", validationLabel: "资料待处理", tone: "warning", statusKey: "pending" },
    { orderNo: "E86", productName: "山野轻暖摇粒绒", category: "服装", tracker: "松子", factory: "昱斌", validationKey: "ready", validationLabel: "可导入", tone: "success", statusKey: "pending" },
    { orderNo: "E87", productName: "轻量防风马甲", category: "服装", tracker: "烧麦", factory: "盛泰", validationKey: "needs-data", validationLabel: "资料待处理", tone: "warning", statusKey: "pending" },
    { orderNo: "E88", productName: "探索家渔夫帽", category: "帽子", tracker: "青椒", factory: "启宏", validationKey: "ready", validationLabel: "可导入", tone: "success", statusKey: "pending" },
    { orderNo: "E89", productName: "云朵软壳冲锋衣", category: "服装", tracker: "大葱", factory: "昱斌", validationKey: "needs-data", validationLabel: "资料待处理", tone: "warning", statusKey: "pending" },
    { orderNo: "E90", productName: "小热皮绒绒裤", category: "服装", tracker: "橄榄", factory: "宇情", validationKey: "ready", validationLabel: "可导入", tone: "success", statusKey: "pending" },
    { orderNo: "E91", productName: "乐园游会吊带包屁衣", category: "服装", tracker: "松子", factory: "昱斌、宇情", validationKey: "needs-data", validationLabel: "资料待处理", tone: "warning", statusKey: "pending" },
    { orderNo: "E72", productName: "轻量防风长裤", category: "服装", tracker: "烧麦", factory: "盛泰", validationKey: "ready", validationLabel: "可导入", tone: "success", statusKey: "ignored" },
    { orderNo: "E73", productName: "向阳遮阳帽", category: "帽子", tracker: "青椒", factory: "启宏", validationKey: "needs-data", validationLabel: "资料待处理", tone: "warning", statusKey: "ignored" },
  ],
};

export const pendingImportDetailData = {
  E81: {
    nearestDue: "2026-08-20",
    totalQuantity: 1800,
    shippedQuantity: 0,
    pendingQuantity: 1800,
    products: [
      { code: "KQ26143", name: "小护甲机能裤", colorSpec: "雾松灰 / 120", factory: "宇情", quantity: 600, validationKey: "ready", validationLabel: "通过" },
      { code: "KQ26143", name: "小护甲机能裤", colorSpec: "雾松灰 / 130", factory: "宇情", quantity: 600, validationKey: "ready", validationLabel: "通过" },
      { code: "KQ26143", name: "小护甲机能裤", colorSpec: "雾松灰 / 140", factory: "宇情", quantity: 600, validationKey: "ready", validationLabel: "通过" },
    ],
  },
  E82: {
    nearestDue: "2026-08-22",
    totalQuantity: 1500,
    shippedQuantity: 0,
    pendingQuantity: 1500,
    products: [
      { code: "KQ26418", name: "云感防晒衣", colorSpec: "云杉绿 / 110", factory: "昱斌", quantity: 500, validationKey: "ready", validationLabel: "通过" },
      { code: "KQ26418", name: "云感防晒衣", colorSpec: "云杉绿 / 120", factory: "昱斌", quantity: 500, validationKey: "needs-data", validationLabel: "资料待处理" },
      { code: "KQ26418", name: "云感防晒衣", colorSpec: "云杉绿 / 130", factory: "昱斌", quantity: 500, validationKey: "ready", validationLabel: "通过" },
    ],
  },
};

export const orderDetailData = {
  "078#": {
    orderNo: "078#",
    productName: "乐园游会吊带包屁衣",
    category: "服装",
    tracker: "松子",
    orderDate: "2026-07-26",
    source: "飞书多维表格导入",
    statusLabel: "已逾期",
    tone: "danger",
    totalQuantity: 3000,
    shippedQuantity: 1380,
    receivedQuantity: 1140,
    pendingQuantity: 1620,
    nearestDue: "2026-08-10",
    remark: "首批优先安排雾松灰 80、90 规格。",
    products: [
      { code: "KQ26143", name: "乐园游会吊带包屁衣", colorSpec: "雾松灰 / 80", quantity: 1000, shippedQuantity: 620, pendingQuantity: 380 },
      { code: "KQ26143", name: "乐园游会吊带包屁衣", colorSpec: "雾松灰 / 90", quantity: 1000, shippedQuantity: 480, pendingQuantity: 520 },
      { code: "KQ26143", name: "乐园游会吊带包屁衣", colorSpec: "雾松灰 / 100", quantity: 1000, shippedQuantity: 280, pendingQuantity: 720 },
    ],
    factories: [
      {
        name: "昱斌",
        contractNo: "20260726-KK-YB",
        allocated: 1800,
        shipped: 1280,
        received: 1140,
        statusLabel: "已逾期",
        tone: "danger",
        contractReady: true,
        lines: [
          { colorSpec: "雾松灰 / 80", dueDate: "2026-08-10", quantity: 600, price: "23.94", shipped: 520, received: 500 },
          { colorSpec: "雾松灰 / 90", dueDate: "2026-08-10", quantity: 600, price: "23.94", shipped: 480, received: 420 },
          { colorSpec: "雾松灰 / 100", dueDate: "2026-08-10", quantity: 600, price: "23.94", shipped: 280, received: 220 },
        ],
      },
      {
        name: "宇情",
        contractNo: "20260726-KK-YQ",
        allocated: 1200,
        shipped: 100,
        received: 0,
        statusLabel: "发货中",
        tone: "info",
        contractReady: true,
        lines: [
          { colorSpec: "雾松灰 / 80", dueDate: "2026-08-18", quantity: 400, price: "", shipped: 100, received: 0 },
          { colorSpec: "雾松灰 / 90", dueDate: "2026-08-18", quantity: 400, price: "", shipped: 0, received: 0 },
          { colorSpec: "雾松灰 / 100", dueDate: "2026-08-18", quantity: 400, price: "", shipped: 0, received: 0 },
        ],
      },
    ],
    shipments: [
      { no: "FH20260812-006", factory: "宇情", shipDate: "2026-08-12", declared: 100, received: "—", statusLabel: "待收货", tone: "warning" },
      { no: "FH20260808-003", factory: "昱斌", shipDate: "2026-08-08", declared: 760, received: 700, statusLabel: "已收货", tone: "success" },
      { no: "FH20260805-001", factory: "昱斌", shipDate: "2026-08-05", declared: 520, received: 440, statusLabel: "已收货", tone: "success" },
    ],
    logs: [
      { time: "2026-08-12 10:18", operator: "宇情工厂", action: "提交发货单 FH20260812-006", source: "工厂小程序" },
      { time: "2026-08-09 17:42", operator: "煎饼", action: "确认收货 FH20260808-003，实际收到 700 件", source: "管理员网页端" },
      { time: "2026-07-26 15:20", operator: "松子", action: "确认导入并发布订单", source: "管理员网页端" },
    ],
  },
};

export function importPendingOrdersAsDrafts(orderNos) {
  const importedAt = new Date().toISOString();
  const orderDate = importedAt.slice(0, 10);
  const requestedOrderNos = new Set(orderNos);
  const importedOrders = pendingImportData.orders.filter((order) => (
    requestedOrderNos.has(order.orderNo)
    && order.statusKey === "pending"
    && order.validationKey === "ready"
  ));

  importedOrders.forEach((order) => {
    const detail = pendingImportDetailData[order.orderNo] ?? {
      nearestDue: "2026-08-25",
      totalQuantity: 1200,
      shippedQuantity: 0,
      pendingQuantity: 1200,
      products: [{
        code: "—",
        name: order.productName,
        colorSpec: "待核对",
        factory: order.factory,
        quantity: 1200,
      }],
    };
    const products = detail.products.map((product) => ({
      code: product.code,
      name: product.name,
      colorSpec: product.colorSpec,
      quantity: product.quantity,
      shippedQuantity: 0,
      pendingQuantity: product.quantity,
    }));
    const factoryNames = [...new Set(detail.products.flatMap((product) => product.factory.split(/[、,，]/).map((value) => value.trim())))];
    const totalQuantity = Number(detail.totalQuantity) || detail.products.reduce((sum, product) => sum + Number(product.quantity || 0), 0);

    order.statusKey = "imported";

    if (!orderListData.orders.some((item) => item.orderNo === order.orderNo)) {
      orderListData.orders.unshift({
        id: `order-${order.orderNo.toLocaleLowerCase("zh-CN")}`,
        orderNo: order.orderNo,
        productName: order.productName,
        category: order.category,
        specSummary: `${detail.products.length} 个颜色 / 规格`,
        tracker: order.tracker,
        factory: order.factory,
        nearestDue: detail.nearestDue,
        shippedPercent: 0,
        shippedText: `0 / ${totalQuantity.toLocaleString("zh-CN")}`,
        receivedPercent: 0,
        receivedText: `0 / ${totalQuantity.toLocaleString("zh-CN")}`,
        statusKey: "draft",
        statusLabel: "草稿",
        tone: "draft",
        overdueDays: 0,
        orderDate,
        updatedAt: importedAt,
      });
    }

    orderDetailData[order.orderNo] = {
      orderNo: order.orderNo,
      productName: order.productName,
      category: order.category,
      tracker: order.tracker,
      orderDate,
      source: "飞书多维表格导入",
      statusKey: "draft",
      statusLabel: "草稿",
      tone: "draft",
      totalQuantity,
      shippedQuantity: 0,
      receivedQuantity: 0,
      pendingQuantity: totalQuantity,
      nearestDue: detail.nearestDue,
      remark: "—",
      products,
      factories: factoryNames.map((factory) => {
        const lines = detail.products
          .filter((product) => product.factory.split(/[、,，]/).map((value) => value.trim()).includes(factory))
          .map((product) => ({
            colorSpec: product.colorSpec,
            dueDate: detail.nearestDue,
            quantity: product.quantity,
            price: "",
            shipped: 0,
            received: 0,
          }));
        return {
          name: factory,
          contractNo: "—",
          allocated: lines.reduce((sum, line) => sum + Number(line.quantity || 0), 0),
          shipped: 0,
          received: 0,
          statusLabel: "草稿",
          tone: "draft",
          contractReady: false,
          lines,
        };
      }),
      shipments: [],
      logs: [{ time: importedAt.replace("T", " ").slice(0, 16), operator: order.tracker, action: "确认导入为草稿", source: "管理员网页端" }],
    };
  });

  return importedOrders;
}
