(function registerMockData() {
  const tasks = [
    {
      id: "task-001",
      orderNo: "E81#",
      productName: "乐园游会吊带包屁衣",
      spec: "蓝色/90",
      contractShipDate: "2026-08-10",
      contractShipDateLabel: "08月10日",
      overdueDays: 8,
      allocated: 450,
      shipped: 450,
      pending: 0,
      progress: 100,
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "task-002",
      orderNo: "E81#",
      productName: "乐园游会吊带包屁衣",
      spec: "蓝色/100",
      contractShipDate: "2026-08-10",
      contractShipDateLabel: "08月10日",
      overdueDays: 8,
      allocated: 450,
      shipped: 450,
      pending: 0,
      progress: 100,
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "task-003",
      orderNo: "E81#",
      productName: "乐园游会吊带包屁衣",
      spec: "杏色/90",
      contractShipDate: "2026-08-10",
      contractShipDateLabel: "08月10日",
      overdueDays: 8,
      allocated: 900,
      shipped: 400,
      pending: 500,
      progress: 44,
      status: "shipping",
      statusLabel: "发货中",
    },
    {
      id: "task-004",
      orderNo: "E92#",
      productName: "小热皮绒绒裤",
      spec: "棕色/100",
      contractShipDate: "2026-08-18",
      contractShipDateLabel: "今天",
      overdueDays: 0,
      allocated: 2000,
      shipped: 1440,
      pending: 560,
      progress: 72,
      status: "shipping",
      statusLabel: "发货中",
    },
    {
      id: "task-005",
      orderNo: "E92#",
      productName: "小热皮绒绒裤",
      spec: "棕色/110",
      contractShipDate: "2026-08-18",
      contractShipDateLabel: "今天",
      overdueDays: 0,
      allocated: 1000,
      shipped: 600,
      pending: 400,
      progress: 60,
      status: "shipping",
      statusLabel: "发货中",
    },
    {
      id: "task-006",
      orderNo: "E106#",
      productName: "云朵软壳冲锋衣",
      spec: "松石绿/110",
      contractShipDate: "2026-08-21",
      contractShipDateLabel: "08月21日",
      overdueDays: 0,
      allocated: 600,
      shipped: 0,
      pending: 600,
      progress: 0,
      status: "pending",
      statusLabel: "待发货",
    },
    {
      id: "task-007",
      orderNo: "E106#",
      productName: "云朵软壳冲锋衣",
      spec: "米白/110",
      contractShipDate: "2026-08-21",
      contractShipDateLabel: "08月21日",
      overdueDays: 0,
      allocated: 500,
      shipped: 0,
      pending: 500,
      progress: 0,
      status: "pending",
      statusLabel: "待发货",
    },
    {
      id: "task-008",
      orderNo: "E78#",
      productName: "秋日摇粒绒外套",
      spec: "雾蓝/120",
      contractShipDate: "2026-08-12",
      contractShipDateLabel: "08月12日",
      overdueDays: 0,
      allocated: 900,
      shipped: 900,
      pending: 0,
      progress: 100,
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "task-009",
      orderNo: "E78#",
      productName: "秋日摇粒绒外套",
      spec: "雾蓝/130",
      contractShipDate: "2026-08-12",
      contractShipDateLabel: "08月12日",
      overdueDays: 0,
      allocated: 900,
      shipped: 900,
      pending: 0,
      progress: 100,
      status: "completed",
      statusLabel: "已完成",
    },
    {
      id: "task-010",
      orderNo: "E35#",
      productName: "轻量防风马甲",
      spec: "橙色/110",
      contractShipDate: "2026-08-24",
      contractShipDateLabel: "08月24日",
      overdueDays: 0,
      allocated: 1400,
      shipped: 0,
      pending: 1400,
      progress: 0,
      status: "pending",
      statusLabel: "待发货",
    },
    {
      id: "task-011",
      orderNo: "E35#",
      productName: "轻量防风马甲",
      spec: "藏青/120",
      contractShipDate: "2026-08-24",
      contractShipDateLabel: "08月24日",
      overdueDays: 0,
      allocated: 1400,
      shipped: 0,
      pending: 1400,
      progress: 0,
      status: "pending",
      statusLabel: "待发货",
    },
  ];

  const statusOptions = [
    ["all", "全部状态"],
    ["pending", "待发货"],
    ["shipping", "发货中"],
    ["completed", "已完成"],
  ];

  window.FactoryPrototypeData = { tasks, statusOptions };
})();