(function registerMockData() {
  const tasks = [
    {
      id: "order-081",
      orderNo: "E81#",
      productSummary: "乐园游会吊带包屁衣",
      specSummary: "蓝色/90、蓝色/100 等3个规格",
      contractShipDate: "2026-08-10",
      contractShipDateLabel: "08月10日",
      overdueDays: 8,
      totalAllocated: 1800,
      totalShipped: 1300,
      totalPending: 500,
      progress: 72,
      status: "shipping",
      statusLabel: "发货中",
      items: [
        { productName: "乐园游会吊带包屁衣", spec: "蓝色/90", allocated: 450, shipped: 450, pending: 0 },
        { productName: "乐园游会吊带包屁衣", spec: "蓝色/100", allocated: 450, shipped: 450, pending: 0 },
        { productName: "乐园游会吊带包屁衣", spec: "杏色/90", allocated: 900, shipped: 400, pending: 500 },
      ],
    },
    {
      id: "order-092",
      orderNo: "E92#",
      productSummary: "小热皮绒绒裤",
      specSummary: "棕色/100、棕色/110",
      contractShipDate: "2026-08-18",
      contractShipDateLabel: "今天",
      overdueDays: 0,
      totalAllocated: 3000,
      totalShipped: 2040,
      totalPending: 960,
      progress: 68,
      status: "shipping",
      statusLabel: "发货中",
      items: [
        { productName: "小热皮绒绒裤", spec: "棕色/100", allocated: 2000, shipped: 1440, pending: 560 },
        { productName: "小热皮绒绒裤", spec: "棕色/110", allocated: 1000, shipped: 600, pending: 400 },
      ],
    },
    {
      id: "order-106",
      orderNo: "E106#",
      productSummary: "云朵软壳冲锋衣",
      specSummary: "松石绿/110、米白/110",
      contractShipDate: "2026-08-21",
      contractShipDateLabel: "08月21日",
      overdueDays: 0,
      totalAllocated: 1100,
      totalShipped: 0,
      totalPending: 1100,
      progress: 0,
      status: "pending",
      statusLabel: "待发货",
      items: [
        { productName: "云朵软壳冲锋衣", spec: "松石绿/110", allocated: 600, shipped: 0, pending: 600 },
        { productName: "云朵软壳冲锋衣", spec: "米白/110", allocated: 500, shipped: 0, pending: 500 },
      ],
    },
    {
      id: "order-078",
      orderNo: "E78#",
      productSummary: "秋日摇粒绒外套",
      specSummary: "雾蓝/120、雾蓝/130",
      contractShipDate: "2026-08-12",
      contractShipDateLabel: "08月12日",
      overdueDays: 0,
      totalAllocated: 1800,
      totalShipped: 1800,
      totalPending: 0,
      progress: 100,
      status: "completed",
      statusLabel: "已完成",
      items: [
        { productName: "秋日摇粒绒外套", spec: "雾蓝/120", allocated: 900, shipped: 900, pending: 0 },
        { productName: "秋日摇粒绒外套", spec: "雾蓝/130", allocated: 900, shipped: 900, pending: 0 },
      ],
    },
    {
      id: "order-035",
      orderNo: "E35#",
      productSummary: "轻量防风马甲等2款",
      specSummary: "橙色/110、杏色/90 等4个规格",
      contractShipDate: "2026-08-24",
      contractShipDateLabel: "08月24日",
      overdueDays: 0,
      totalAllocated: 2800,
      totalShipped: 0,
      totalPending: 2800,
      progress: 0,
      status: "pending",
      statusLabel: "待发货",
      items: [
        { productName: "轻量防风马甲", spec: "橙色/110", allocated: 1400, shipped: 0, pending: 1400 },
        { productName: "乐园游会吊带包屁衣", spec: "杏色/90", allocated: 1400, shipped: 0, pending: 1400 },
      ],
    },
  ];

  const statusOptions = [
    ["incomplete", "未完成"],
    ["all", "全部状态"],
    ["pending", "待发货"],
    ["shipping", "发货中"],
    ["completed", "已完成"],
  ];

  window.FactoryPrototypeData = { tasks, statusOptions };
})();
