<template>
  <AdminShell>
    <article class="order-workspace order-detail-page">
      <section v-if="loading" class="section-card page-state">正在加载订单详情…</section>
      <section v-else-if="!order" class="section-card page-error">{{ errorMessage || '订单不存在' }}</section>
      <template v-else>
        <header class="detail-toolbar section-card"><button class="back-link" type="button" @click="$router.push('/orders')">‹ 返回</button><div class="detail-actions"><span class="order-status" :data-status="order.displayStatus">{{ order.displayStatus }}</span><RouterLink v-if="order.lifecycle === 'DRAFT'" class="order-secondary-button" :to="`/orders/${order.orderId}/edit`">编辑草稿</RouterLink><button v-if="order.lifecycle === 'DRAFT'" class="order-primary-button" @click="openAction('publish')">发布订单</button><button v-if="order.lifecycle === 'PUBLISHED'" class="order-secondary-button" @click="openAction('withdraw')">撤回订单</button><button v-if="order.lifecycle === 'PUBLISHED'" class="order-primary-button" @click="openAction('complete')">确认订单完成</button><button v-if="order.lifecycle === 'COMPLETED'" class="order-secondary-button" @click="openAction('reopen')">撤销完成</button><button v-if="order.lifecycle !== 'COMPLETED'" class="danger-button" @click="openAction('delete')">删除订单</button></div></header>
        <section class="section-card detail-overview"><header class="section-heading"><div><p class="page-kicker">订单详情</p><h1>{{ order.orderNo }}</h1></div></header><dl class="overview-grid"><div><dt>订单日期</dt><dd>{{ order.orderDate }}</dd></div><div><dt>跟单人员</dt><dd>{{ order.tracker }}</dd></div><div><dt>合同出货时间</dt><dd>{{ order.contractShipDate }}</dd></div><div><dt>来源</dt><dd>{{ order.source === 'manual' ? '手工新建' : '飞书导入' }}</dd></div><div><dt>订单数量</dt><dd>{{ number(order.totalQuantity) }}</dd></div><div><dt>已发数量</dt><dd>{{ number(order.shippedQuantity) }}</dd></div><div><dt>未发数量</dt><dd>{{ number(order.pendingQuantity) }}</dd></div><div><dt>发货进度</dt><dd>{{ order.progressPercent }}%</dd></div></dl><p v-if="order.validationIssues.length" class="validation-callout">{{ order.validationIssues.join('；') }}</p></section>
        <section class="section-card"><header class="section-heading"><h2>订单明细</h2></header><div class="table-scroll"><table class="order-table"><thead><tr><th>产品编码</th><th>产品名称</th><th>颜色/规格</th><th>订单数量</th><th>已发数量</th><th>未发数量</th><th>发货进度</th></tr></thead><tbody><tr v-for="line in order.lines" :key="line.orderLineId"><td>{{ line.skuId }}</td><td>{{ line.productName }}</td><td>{{ line.propertiesValue }}</td><td>{{ number(line.orderQuantity) }}</td><td>{{ number(line.shippedQuantity) }}</td><td>{{ number(line.pendingQuantity) }}</td><td>{{ line.progressPercent }}%</td></tr></tbody></table></div></section>
        <section class="section-card"><header class="section-heading"><h2>工厂派工与进度</h2></header><div class="factory-progress-grid"><article v-for="factory in order.factoryProgress" :key="factory.factoryId"><header><strong>{{ factory.factoryName }}</strong><span>{{ factory.progressPercent }}%</span></header><dl><div><dt>下单数量</dt><dd>{{ number(factory.orderQuantity) }}</dd></div><div><dt>已发数量</dt><dd>{{ number(factory.shippedQuantity) }}</dd></div><div><dt>未发数量</dt><dd>{{ number(factory.pendingQuantity) }}</dd></div></dl></article><div v-if="!order.factoryProgress.length" class="empty-state"><strong>暂未派工</strong></div></div></section>
        <section class="section-card"><header class="section-heading"><h2>关联发货单</h2></header><div class="empty-state"><strong>当前订单暂无关联发货单</strong><p>S07 接入正式发货单后显示。</p></div></section>
        <section class="section-card"><header class="section-heading"><h2>操作日志</h2></header><div v-if="logs.length" class="audit-list"><article v-for="(log, index) in logs" :key="`${log.createdAt}-${index}`"><strong>{{ actionLabel(log.action) }}</strong><span>{{ log.createdAt.replace('T', ' ').slice(0, 16) }} · {{ log.sourceTerminal === 'web' ? '管理员网页端' : log.sourceTerminal }}</span></article></div><div v-else class="empty-state"><strong>暂无操作日志</strong></div></section>
      </template>

      <div v-if="pendingAction && order" class="modal-backdrop" role="dialog" aria-modal="true"><section class="modal action-modal"><header><h2>{{ modalTitle }}</h2><button type="button" @click="pendingAction = null">×</button></header><div class="modal-body"><p>{{ modalDescription }}</p><dl v-if="pendingAction === 'complete'" class="completion-summary"><div><dt>订单数量</dt><dd>{{ number(order.totalQuantity) }}</dd></div><div><dt>已发数量</dt><dd>{{ number(order.shippedQuantity) }}</dd></div><div><dt>未发数量</dt><dd>{{ number(order.pendingQuantity) }}</dd></div></dl><label v-if="pendingAction === 'reopen'" class="reopen-field">撤销原因<textarea v-model="reopenReason" maxlength="500" placeholder="请填写撤销完成原因"></textarea></label><p v-if="actionError" class="page-error">{{ actionError }}</p></div><footer><button class="order-secondary-button" type="button" @click="pendingAction = null">取消</button><button class="order-primary-button" type="button" :disabled="acting || (pendingAction === 'reopen' && !reopenReason.trim())" @click="confirmAction">{{ acting ? '处理中…' : '确认' }}</button></footer></section></div>
    </article>
  </AdminShell>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";

import { ApiError, orderApi, type AuditLogList, type Order } from "@/api/client";
import AdminShell from "@/components/AdminShell.vue";

type Action = "publish" | "withdraw" | "delete" | "complete" | "reopen";
const route = useRoute(); const router = useRouter(); const orderId = String(route.params.orderId);
const order = ref<Order | null>(null); const logs = ref<AuditLogList["items"]>([]); const loading = ref(true); const errorMessage = ref(""); const pendingAction = ref<Action | null>(null); const reopenReason = ref(""); const actionError = ref(""); const acting = ref(false);
const number = (value: number) => value.toLocaleString("zh-CN");
const modalTitle = computed(() => ({ publish: "发布订单", withdraw: "撤回订单", delete: "删除订单", complete: "确认订单完成", reopen: "撤销完成" }[pendingAction.value ?? "publish"]));
const modalDescription = computed(() => pendingAction.value === "publish" ? "发布后工厂将看到各自派工任务，确认发布？" : pendingAction.value === "withdraw" ? "撤回后订单恢复为草稿，工厂任务将不可见。" : pendingAction.value === "delete" ? "删除后订单不再出现在订单列表和工厂任务中。" : pendingAction.value === "complete" ? "请核对数量摘要。完成状态不会根据发货数量自动产生。" : "撤销后订单恢复为正式订单，并按当前日期重新计算状态。" );
const actionLabel = (value: string) => ({ "order.draft_created": "创建订单草稿", "order.draft_updated": "保存订单草稿", "order.published": "发布订单", "order.withdrawn": "撤回订单", "order.deleted": "删除订单", "order.complete": "确认订单完成", "order.reopen": "撤销完成" }[value] ?? value);
function openAction(action: Action) { pendingAction.value = action; reopenReason.value = ""; actionError.value = ""; }
async function load() { loading.value = true; try { const [detail, audit] = await Promise.all([orderApi.get(orderId), orderApi.auditLogs(orderId)]); order.value = detail; logs.value = audit.items; } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : "订单详情加载失败"; } finally { loading.value = false; } }
async function confirmAction() { if (!order.value || !pendingAction.value) return; acting.value = true; actionError.value = ""; try { const action = pendingAction.value; if (action === "delete") { await orderApi.delete(orderId); await router.replace("/orders"); return; } if (action === "publish") await orderApi.publish(orderId, order.value.version); if (action === "withdraw") await orderApi.withdraw(orderId); if (action === "complete") await orderApi.complete(orderId); if (action === "reopen") await orderApi.reopen(orderId, reopenReason.value); pendingAction.value = null; await load(); } catch (error) { actionError.value = error instanceof ApiError ? error.message : "订单操作失败"; } finally { acting.value = false; } }
onMounted(load);
</script>
