<template>
  <AdminShell title="待导入订单"><article class="order-list-page pending-import-page">
    <section class="order-list-filter-card" aria-label="待导入订单筛选">
      <nav class="order-status-tabs"><button class="order-status-tab" :class="{ 'is-active': status === 'PENDING' }" type="button" @click="switchStatus('PENDING')">待处理</button><button class="order-status-tab" :class="{ 'is-active': status === 'IMPORTED' }" type="button" @click="switchStatus('IMPORTED')">已导入</button></nav>
      <form class="order-filter-form import-search-form" @submit.prevent="search"><div class="order-filter-row pending-import-filter-row">
        <label class="order-list-search-field"><span class="sr-only">搜索订单编号或产品名称</span><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4 4" /></svg><input v-model="keyword" type="search" placeholder="输入订单编号或产品名称" /></label>
        <label class="order-select-field"><span class="sr-only">分类</span><select v-model="category" class="import-category-filter"><option value="">全部分类</option><option value="服装">服装</option><option value="帽子">帽子</option></select></label>
        <div class="order-multiselect"><button class="order-multiselect-trigger" type="button" @click="factoryOpen = !factoryOpen"><span>{{ multiLabel(factoryNames, '全部工厂', '个工厂') }}</span><span>⌄</span></button><div class="order-multiselect-menu" :class="{ 'is-open': factoryOpen }"><div class="order-multiselect-title">选择工厂（可多选）</div><label v-for="name in factoryOptions" :key="name" class="order-multiselect-option"><input v-model="factoryNames" type="checkbox" :value="name" /><span>{{ name }}</span></label></div></div>
        <div class="order-multiselect order-tracker-multiselect"><button class="order-multiselect-trigger" type="button" @click="trackerOpen = !trackerOpen"><span>{{ multiLabel(selectedTrackers, '全部跟单人员', '位跟单人员') }}</span><span>⌄</span></button><div class="order-multiselect-menu" :class="{ 'is-open': trackerOpen }"><div class="order-multiselect-title">选择跟单人员（可多选）</div><label v-for="name in trackers" :key="name" class="order-multiselect-option"><input v-model="selectedTrackers" type="checkbox" :value="name" /><span>{{ name }}</span></label></div></div>
        <label class="order-select-field order-validation-field"><span class="sr-only">校验状态</span><select v-model="validationState"><option value="">全部校验状态</option><option value="READY">可导入</option><option value="INVALID">资料待处理</option></select></label>
        <button class="order-secondary-button" type="button" @click="reset">重置</button><button class="order-primary-button" type="submit">搜索</button>
      </div></form>
    </section>
    <p v-if="runMessage" class="import-run-message" role="status">{{ runMessage }}</p><p v-if="errorMessage" class="page-error">{{ errorMessage }}</p>
    <section class="section-card order-list-card import-table-card" aria-labelledby="pending-import-title">
      <header class="order-list-card-header import-table-title-row"><div class="order-list-heading"><h1 id="pending-import-title">待导入订单</h1></div><div class="order-list-header-actions"><span class="pending-import-fetch-meta">上次成功获取：<strong>{{ lastSuccess ? formatTime(lastSuccess) : '—' }}</strong></span><button class="order-secondary-button pending-import-fetch-button" type="button" :disabled="fetching" @click="fetchOrders">{{ fetching ? "正在获取…" : "获取飞书新订单" }}</button><button class="order-primary-button" type="button" :disabled="selected.size === 0" @click="batchDialogOpen = true">批量导入为草稿</button></div></header>
      <p v-if="loading" class="page-state">正在加载候选订单…</p><div v-else class="table-scroll"><table class="pending-import-table data-grid-table import-candidate-table">
        <thead><tr><th class="pending-import-select-column"><input type="checkbox" aria-label="全选当前页可导入订单" :checked="allReadySelected" :disabled="status !== 'PENDING' || readyItems.length === 0" @change="togglePage" /></th><th class="import-sequence-column">序号</th><th v-for="column in columns" :key="column.key"><TableSortButton :label="column.label" :field="column.key" :sort-by="sortBy" :sort-order="sortOrder" @sort="toggleSort" /></th><th>操作</th></tr></thead>
        <tbody><tr v-for="(item, index) in items" :key="item.candidateId" :class="{ 'is-selected': selected.has(item.candidateId) }"><td class="pending-import-select-cell"><input type="checkbox" :aria-label="`选择订单 ${item.orderNo}`" :checked="selected.has(item.candidateId)" :disabled="status !== 'PENDING' || item.validationState !== 'READY'" @change="toggleOne(item.candidateId)" /></td><td class="import-sequence-column">{{ (page - 1) * pageSize + index + 1 }}</td><td><RouterLink class="row-link" :to="`/orders/import/${item.candidateId}`">{{ item.orderNo }}</RouterLink></td><td class="order-product-summary"><strong>{{ productNames(item) }}</strong></td><td><template v-if="categories(item).length"><span v-for="name in categories(item)" :key="name" class="category-tag" :class="name === '服装' ? 'is-clothing' : 'is-hat'">{{ name }}</span></template><span v-else>—</span></td><td><span class="tracker-tag" :data-tracker="item.tracker">{{ item.tracker ?? '—' }}</span></td><td>{{ factorySummary(item) }}</td><td><span class="status-badge" :class="item.validationState === 'READY' ? 'is-success' : 'is-warning'">{{ item.validationState === "READY" ? "可导入" : issueLabel(item.validationIssues) }}</span></td><td><RouterLink class="order-view-button" :to="`/orders/import/${item.candidateId}`">详情</RouterLink><button v-if="status === 'PENDING'" class="order-delete-button" type="button" @click="deleteTarget = item">删除</button></td></tr><tr v-if="items.length === 0"><td colspan="9"><div class="empty-state"><div><strong>没有符合当前条件的订单</strong><p>可以调整搜索词或筛选条件后重新查询。</p></div></div></td></tr></tbody>
      </table></div>
      <footer class="order-list-footer"><span>每页展示 {{ pageSize }} 条待导入订单。</span><nav class="order-pagination"><span class="order-page-total">共 {{ total }} 条</span><button class="order-page-button" type="button" :disabled="page === 1" @click="go(page - 1)">‹</button><span class="order-page-button is-current">{{ page }}</span><button class="order-page-button" type="button" :disabled="page * pageSize >= total" @click="go(page + 1)">›</button></nav></footer>
    </section>
    <div v-if="deleteTarget" class="detail-confirm-layer"><button class="detail-confirm-backdrop" type="button" aria-label="取消删除" @click="deleteTarget = null"></button><section class="detail-confirm-dialog" role="dialog" aria-modal="true"><h2>确认删除待导入订单</h2><p>确认删除订单 <strong>{{ deleteTarget.orderNo }}</strong>？只从本系统待处理列表排除，不删除飞书数据，且后续不再出现。</p><div class="detail-confirm-actions"><button class="detail-outline-button" type="button" @click="deleteTarget = null">取消</button><button class="order-delete-confirm-button" type="button" @click="excludeOne">确认删除</button></div></section></div>
    <div v-if="batchDialogOpen" class="detail-confirm-layer"><button class="detail-confirm-backdrop" type="button" aria-label="取消批量导入" @click="batchDialogOpen = false"></button><section class="detail-confirm-dialog" role="dialog" aria-modal="true"><h2>确认批量导入为草稿</h2><p>确认将已选 <strong>{{ selected.size }}</strong> 个订单导入跟单系统？导入后将生成草稿订单。</p><p>{{ selectedOrderNos }}</p><div class="detail-confirm-actions"><button class="detail-outline-button" type="button" @click="batchDialogOpen = false">取消</button><button class="detail-primary-button" type="button" @click="confirmSelected">确认导入为草稿</button></div></section></div>
  </article></AdminShell>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { ApiError, identityApi, orderImportApi, type ImportCandidate, type ImportRun } from "@/api/client";
import AdminShell from "@/components/AdminShell.vue"; import TableSortButton from "@/components/TableSortButton.vue";
const trackers = ["烧麦", "松子", "橄榄", "大葱", "青椒"]; const columns = [{ key: "orderNo", label: "订单编号" }, { key: "productName", label: "产品名称" }, { key: "category", label: "分类" }, { key: "tracker", label: "跟单人员" }, { key: "factory", label: "工厂" }, { key: "validationState", label: "校验状态" }];
const pageSize = 10; const status = ref<"PENDING" | "IMPORTED">("PENDING"); const keyword = ref(""); const category = ref(""); const factoryNames = ref<string[]>([]); const selectedTrackers = ref<string[]>([]); const validationState = ref(""); const factoryOptions = ref<string[]>([]); const factoryOpen = ref(false); const trackerOpen = ref(false);
const items = ref<ImportCandidate[]>([]); const total = ref(0); const page = ref(1); const selected = ref(new Set<string>()); const deleteTarget = ref<ImportCandidate | null>(null); const batchDialogOpen = ref(false); const sortBy = ref("default"); const sortOrder = ref<"asc" | "desc">("asc");
const loading = ref(true); const fetching = ref(false); const errorMessage = ref(""); const runMessage = ref(""); const lastSuccess = ref<string | null>(null); let pollTimer: ReturnType<typeof setTimeout> | undefined;
const readyItems = computed(() => items.value.filter((item) => status.value === "PENDING" && item.validationState === "READY")); const allReadySelected = computed(() => readyItems.value.length > 0 && readyItems.value.every((item) => selected.value.has(item.candidateId))); const selectedOrderNos = computed(() => items.value.filter((item) => selected.value.has(item.candidateId)).map((item) => item.orderNo).join("、"));
const multiLabel = (values: string[], empty: string, unit: string) => values.length === 0 ? empty : values.length === 1 ? values[0] : `已选 ${values.length} ${unit}`; const productNames = (item: ImportCandidate) => [...new Set(item.lines.map((line) => line.productName).filter(Boolean))].join("、") || "—"; const factorySummary = (item: ImportCandidate) => [...new Set(item.lines.map((line) => line.factoryName).filter(Boolean))].join("、") || "—";
const categories = (item: ImportCandidate) => item.category?.split("、").filter(Boolean) ?? [];
const issueLabel = (issues: string[]) => issues.length ? "资料待处理" : "可导入"; const formatTime = (value: string) => new Date(value).toLocaleString("zh-CN", { hour12: false });
async function load() { loading.value = true; errorMessage.value = ""; try { const result = await orderImportApi.list({ status: status.value, keyword: keyword.value.trim(), category: category.value || undefined, factoryNames: factoryNames.value, trackers: selectedTrackers.value, validationState: validationState.value || undefined, sortBy: sortBy.value, sortOrder: sortOrder.value, page: page.value, pageSize }); items.value = result.items; total.value = result.total; } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : "候选订单加载失败"; } finally { loading.value = false; } }
async function search() { page.value = 1; await load(); } async function reset() { keyword.value = ""; category.value = ""; factoryNames.value = []; selectedTrackers.value = []; validationState.value = ""; sortBy.value = "default"; sortOrder.value = "asc"; selected.value = new Set(); await search(); } async function switchStatus(value: "PENDING" | "IMPORTED") { status.value = value; selected.value = new Set(); await search(); } async function go(value: number) { page.value = value; await load(); }
function toggleOne(id: string) { const next = new Set(selected.value); if (next.has(id)) next.delete(id); else next.add(id); selected.value = next; } function togglePage() { const next = new Set(selected.value); if (allReadySelected.value) readyItems.value.forEach((item) => next.delete(item.candidateId)); else readyItems.value.forEach((item) => next.add(item.candidateId)); selected.value = next; }
async function toggleSort(field: string) { if (sortBy.value === field) sortOrder.value = sortOrder.value === "asc" ? "desc" : "asc"; else { sortBy.value = field; sortOrder.value = "asc"; } await search(); } async function excludeOne() { if (!deleteTarget.value) return; try { await orderImportApi.exclude(deleteTarget.value.candidateId); selected.value.delete(deleteTarget.value.candidateId); deleteTarget.value = null; await load(); } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : "删除失败"; } }
async function confirmSelected() { const result = await orderImportApi.confirmBatch([...selected.value]); const succeeded = result.items.filter((item) => item.succeeded).length; runMessage.value = `批量导入完成：成功 ${succeeded}，失败 ${result.items.length - succeeded}`; batchDialogOpen.value = false; selected.value = new Set(); await load(); }
async function poll(run: ImportRun) { if (["SUCCEEDED", "FAILED"].includes(run.status)) { fetching.value = false; runMessage.value = run.status === "SUCCEEDED" ? `获取完成：新增 ${run.candidatesCreated} 个，已存在/跳过 ${run.candidatesUpdated + run.skippedRecords} 个，失败 ${run.failedRecords} 个。` : "获取失败，请检查飞书应用配置后重试。"; if (run.status === "SUCCEEDED") { lastSuccess.value = run.finishedAt; await load(); } return; } pollTimer = setTimeout(async () => { try { await poll(await orderImportApi.getRun(run.runId)); } catch { fetching.value = false; errorMessage.value = "获取任务状态失败"; } }, 1200); }
async function fetchOrders() { fetching.value = true; errorMessage.value = ""; try { await poll(await orderImportApi.createRun()); } catch (error) { fetching.value = false; errorMessage.value = error instanceof ApiError ? error.message : "无法启动获取任务"; } }
onMounted(async () => { const factories = await identityApi.listFactories().catch(() => null); factoryOptions.value = factories?.items.map((item) => item.factoryName) ?? []; const latest = await orderImportApi.latestRun().catch(() => null); if (latest?.status === "SUCCEEDED") lastSuccess.value = latest.finishedAt; else if (latest && !["FAILED", "SUCCEEDED"].includes(latest.status)) { fetching.value = true; void poll(latest); } await load(); }); onBeforeUnmount(() => { if (pollTimer) clearTimeout(pollTimer); });
</script>
