<template>
  <AdminShell :title="candidate ? `待导入订单详情 · ${candidate.orderNo}` : '待导入订单详情'">
    <article v-if="candidate" class="order-detail-page pending-import-detail-page">
      <section class="section-card detail-overview-card">
        <header class="detail-page-header">
          <button class="detail-back-button" type="button" @click="router.push('/orders/import')"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m15 18-6-6 6-6" /></svg><span>返回</span></button>
          <div class="detail-title-row pending-import-detail-actions"><span class="status-badge" :class="candidate.status === 'IMPORTED' ? 'is-success' : candidate.validationState === 'READY' ? 'is-success' : 'is-warning'"><i aria-hidden="true"></i>{{ candidate.status === "IMPORTED" ? "已导入" : candidate.validationState === "READY" ? "可导入" : "资料待处理" }}</span><button v-if="candidate.status === 'PENDING'" class="detail-primary-button" type="button" :disabled="candidate.validationState !== 'READY'" :title="candidate.validationState === 'READY' ? '确认导入当前候选为草稿' : '请先处理全部待处理资料'" @click="confirmOpen = true">确认导入为草稿</button></div>
        </header>
        <div class="detail-overview-content"><dl class="detail-summary-grid" aria-label="待导入订单概览"><div><dt>分类</dt><dd><span class="category-tag" :class="candidate.category === '帽子' ? 'is-hat' : 'is-clothing'">{{ candidate.category ?? "—" }}</span></dd></div><div><dt>跟单人员</dt><dd><span class="tracker-tag" :data-tracker="candidate.tracker">{{ candidate.tracker ?? "—" }}</span></dd></div><div><dt>合同出货时间</dt><dd class="detail-due-date">{{ candidate.contractShipDate ?? "—" }}</dd></div><div><dt>订单数量</dt><dd class="detail-summary-number">{{ number(candidate.totalQuantity) }}</dd></div><div><dt>已发数量</dt><dd class="detail-summary-number">{{ number(candidate.shippedQuantity) }}</dd></div><div><dt>未发数量</dt><dd class="detail-summary-number">{{ number(candidate.pendingQuantity) }}</dd></div></dl><p v-if="candidate.validationIssues.length" class="validation-callout">{{ issueText(candidate.validationIssues) }}</p></div>
      </section>
      <section class="section-card detail-section-card"><header class="detail-section-header"><h2>订单明细</h2></header><div class="detail-table-scroll"><table class="detail-data-table product-detail-table pending-import-detail-table data-grid-table"><thead><tr><th class="detail-sequence-column">序号</th><th class="detail-image-column">图片</th><th v-for="column in lineColumns" :key="column.key"><TableSortButton :label="column.label" :field="column.key" :sort-by="lineSortBy" :sort-order="lineSortOrder" @sort="toggleLineSort" /></th></tr></thead><tbody><tr v-for="(line, index) in sortedLines" :key="line.candidateLineId"><td class="detail-sequence-cell">{{ index + 1 }}</td><td class="detail-image-cell"><span class="product-thumb" aria-label="产品图片未上传"><svg viewBox="0 0 28 34" fill="none" aria-hidden="true"><path d="m9 5 5-2 5 2 5 6-4 3v15H8V14l-4-3 5-6Z" /><path d="M11 5c.6 2 1.6 3 3 3s2.4-1 3-3" /></svg></span></td><td class="detail-code">{{ line.sourceSkuId ?? "—" }}</td><td><strong class="detail-product-name">{{ line.productName ?? "—" }}</strong></td><td>{{ line.propertiesValue ?? "—" }}</td><td>{{ line.factoryName ?? "—" }}</td><td class="detail-number">{{ line.orderQuantity == null ? "—" : number(line.orderQuantity) }}</td><td class="detail-number">{{ number(line.shippedQuantity) }}</td><td class="detail-number">{{ number(line.pendingQuantity) }}</td><td><span class="detail-progress"><span><i :style="{ width: `${progress(line)}%` }"></i></span><em>{{ progress(line) }}%</em></span></td><td><span class="status-badge" :class="line.validationIssues.length ? 'is-warning' : 'is-success'"><i aria-hidden="true"></i>{{ line.validationIssues.length ? issueText(line.validationIssues) : "通过" }}</span></td></tr></tbody></table></div></section>
      <div v-if="confirmOpen" class="detail-confirm-layer"><button class="detail-confirm-backdrop" type="button" aria-label="取消确认导入" @click="confirmOpen = false"></button><section class="detail-confirm-dialog" role="dialog" aria-modal="true"><h2>确认导入为草稿</h2><p>确认将候选订单 <strong>{{ candidate.orderNo }}</strong> 导入跟单系统？确认后将在订单列表中生成草稿订单，发布前工厂不可见。</p><div class="detail-confirm-actions"><button class="detail-outline-button" type="button" @click="confirmOpen = false">取消</button><button class="detail-primary-button" type="button" @click="confirmCandidate">确认导入为草稿</button></div></section></div>
    </article>
    <p v-else-if="loading" class="page-state">正在加载候选订单…</p><p v-else class="page-error">{{ errorMessage }}</p>
  </AdminShell>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from "vue"; import { useRoute, useRouter } from "vue-router";
import { ApiError, orderImportApi, type ImportCandidate } from "@/api/client"; import AdminShell from "@/components/AdminShell.vue"; import TableSortButton from "@/components/TableSortButton.vue";
const route = useRoute(); const router = useRouter(); const candidate = ref<ImportCandidate | null>(null); const loading = ref(true); const errorMessage = ref(""); const confirmOpen = ref(false);
const issueLabels: Record<string, string> = { PRODUCT_VARIANT_NOT_MATCHED: "产品资料未匹配", FACTORY_NOT_MATCHED: "工厂资料未匹配", FACTORY_HAS_NO_ENABLED_USER: "工厂没有已启用账号", INVALID_TRACKER: "跟单人员无效", INVALID_ORDER_QUANTITY: "下单数量无效", INVALID_INITIAL_SHIPPED_QUANTITY: "初始已发数量无效", INITIAL_SHIPPED_EXCEEDS_ORDER_QUANTITY: "初始已发数量大于订单数量", INCONSISTENT_CONTRACT_SHIP_DATE: "合同出货时间不一致" };
const lineColumns = [{ key: "sourceSkuId", label: "产品编码" }, { key: "productName", label: "产品名称" }, { key: "propertiesValue", label: "颜色/规格" }, { key: "factoryName", label: "工厂" }, { key: "orderQuantity", label: "下单数量" }, { key: "shippedQuantity", label: "已发数量" }, { key: "pendingQuantity", label: "未发数量" }, { key: "progress", label: "发货进度" }, { key: "validation", label: "校验结果" }];
const lineSortBy = ref("sourceSkuId"); const lineSortOrder = ref<"asc" | "desc">("asc");
const number = (value: number) => value.toLocaleString("zh-CN");
const issueText = (issues: string[]) => issues === candidate.value?.validationIssues ? issues.map((issue) => issueLabels[issue] ?? "资料待处理").join("；") : "未通过"; const progress = (line: ImportCandidate["lines"][number]) => !line.orderQuantity ? 0 : Math.round(line.shippedQuantity * 100 / line.orderQuantity);
const sortedLines = computed(() => [...(candidate.value?.lines ?? [])].sort((left, right) => { const value = (line: ImportCandidate["lines"][number]) => lineSortBy.value === "progress" ? progress(line) : lineSortBy.value === "validation" ? issueText(line.validationIssues) : line[lineSortBy.value as keyof typeof line] ?? ""; return String(value(left)).localeCompare(String(value(right)), "zh-CN", { numeric: true }) * (lineSortOrder.value === "asc" ? 1 : -1); }));
function toggleLineSort(field: string) { if (lineSortBy.value === field) lineSortOrder.value = lineSortOrder.value === "asc" ? "desc" : "asc"; else { lineSortBy.value = field; lineSortOrder.value = "asc"; } }
async function confirmCandidate() { if (!candidate.value) return; try { await orderImportApi.confirm(candidate.value.candidateId); await router.push({ path: "/orders/import", query: { imported: candidate.value.orderNo } }); } catch (error) { confirmOpen.value = false; errorMessage.value = error instanceof ApiError ? error.message : "导入失败"; } }
onMounted(async () => { try { candidate.value = await orderImportApi.get(String(route.params.candidateId)); } catch (error) { errorMessage.value = error instanceof ApiError ? error.message : "候选订单不存在"; } finally { loading.value = false; } });
</script>
